# Generated by Django 6.0.4 on 2026-04-25 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slots',
            options={'ordering': ['date', 'start_time'], 'verbose_name_plural': 'Slots'},
        ),
    ]
